baseurl = "https://3aair.com/"
languageCode = "en-us"
title = "AAA Air Conditioning | Daphne, AL 36526"
copyright = "Â© 2021 AAA Air Conditioning, LLC"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
